### ISSUE TITLE
KeepSwinging Not Swinging

### ISSUE THREAD

**Issue by mhauskn** [ItsAlxl/darktide-mods#61]
Despite my best efforts I can't get KeepSwinging to work. The swinging icon will toggle on/off when I press the corresponding hotkey to enable/disable it, but no attacks happen. I've tried nearly all the mods settings trying to get it to do any type of swing, but no matter what settings I choose, it just doesn't do anything (aside from toggling the keepswinging icon). My attacks still work as normal and seem to be completely unchanged by having the mod.

The mod is enabled in the mods framework and other mods I have are working fine - so I'm not sure what I'm doing wrong here.

Are there any debug messages I could view to figure out what could be going wrong?

Appreciate any help!

**Comment by ItsAlxl** [comment]
So far, anytime someone has had issues with KeepSwinging or FullAuto like you've described (the icon highlights but the mod doesn't apparently do anything), it's been due to an out-of-date DMF. The mod doesn't have debugging messages in it normally, but you can litter them around the files yourself if you like. For starters, I'd just add a `mod:echo("spam")` at the top of `_input_action_hook` in `KeepSwinging.lua` like so:
```lua
local _input_action_hook = function(func, self, action_name)
    mod:echo("spam")
    local val = func(self, action_name)
    local current_action_set = ACTION_SETS[current_action]
    . . .
end
```
If your chat/console log doesn't immediately fill up with an overwhelming horde of "spam", then the only explanation I can think of is an outdated DMF. If it *does* spam you but the mod still doesn't work, I'll make a version with some more comprehensive debugging messages to help narrow the issue down.

**Comment by mhauskn** [comment]
You're right - it was an outdated DMF. I had mistakenly downloaded an old version of DMF and assumed that mine was current.
