### ISSUE TITLE
[Bug] [Assets] Shirtless Mod

### ISSUE THREAD

**Issue by Vel-San** [ItsAlxl/darktide-mods#80]
Ahoy,

I've noticed that 'Shirtless' currently doesn't show the torso in Morningstar - is that intended? Is there no way to show default_upperbody instead of empty_upperbody? I am not even sure whether the changes are properly reflected in-game too as it has been ages since the last update.

https://github.com/ItsAlxl/darktide-mods/blob/e6f8e930edb8d5187bf959eea34b960d56d2583b/Shirtless/scripts/mods/Shirtless/Shirtless.lua#L5C56-L5C92

Also a side-note that your README needs to be updated to remove the Shirtless mod as it has been deleted from Nexus, I suppose to lessed the exposure.

**Comment by ItsAlxl** [comment]
Oh yeah, I should update the readme lol. Thanks for the reminder. I removed the mod from Nexus cuz it was bugged and I didn't feel like fixing it. I don't remember the nature of the bug; this might've been it!

For the sake of clarity, the mod is compliant with Fatshark's modding policy because you do not appear shirtless to other people with it. It's purely client-side, so it doesn't force a modded experience onto other players, so it's all good.

**Comment by Vel-San** [comment]
> Oh yeah, I should update the readme lol. Thanks for the reminder. I removed the mod from Nexus cuz it was bugged and I didn't feel like fixing it. I don't remember the nature of the bug; this might've been it!
> 
> For the sake of clarity, the mod is compliant with Fatshark's modding policy because you do not appear shirtless to other people with it. It's purely client-side, so it doesn't force a modded experience onto other players, so it's all good.

I figured! Haha yeah, I tried to fix it but don't have time to dig around - however I have modified the mod to also have options in-game in the ESC mods menu, and added the LowerBody selection too.

Thanks - I have mentioned you as well in the credits too <3
